apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: tivix/docker-nginx:v11
          command: ['/bin/sh', '-c', 'echo "Host: ${HOSTNAME}" >> /code/html/index.html && exec /code/docker-entrypoint.sh']
          ports:
            - containerPort: 80
          env:
            - name: MAINTENANCE
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: nginx-test
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - port: 80
      targetPort: 80
